<!DOCTYPE html>
<html lang="th">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Gold Multi-TF Strategy v23 - Updated Mar 2026</title>
    <style>
        body { font-family: Arial, sans-serif; max-width: 1200px; margin: 0 auto; padding: 20px; background: #f4f4f4; color: #333; }
        h1 { color: #d4af37; text-align: center; }
        h2 { color: #b8860b; border-bottom: 2px solid #d4af37; padding-bottom: 10px; }
        table { width: 100%; border-collapse: collapse; margin: 20px 0; background: white; box-shadow: 0 2px 10px rgba(0,0,0,0.1); }
        th, td { padding: 12px; text-align: left; border-bottom: 1px solid #ddd; }
        th { background: #d4af37; color: white; }
        .bullish { background: #d4edda; color: #155724; }
        .bearish { background: #f8d7da; color: #721c24; }
        .trend-box { padding: 15px; margin: 10px 0; border-radius: 8px; font-weight: bold; }
        .current-price { font-size: 24px; text-align: center; margin: 20px 0; padding: 20px; background: linear-gradient(45deg, #ffd700, #d4af37); border-radius: 10px; color: #333; }
    </style>
</head>
<body>
    <h1>🪙 Gold Multi-Timeframe Strategy v23</h1>
    <p style="text-align: center; font-size: 18px;">อัพเดทข้อมูลเทรนด์จริง - 29 มี.ค. 2026 | XAUUSD ~4,495 USD (ลง 15.55% เดือนนี้)</p>
    
    <div class="current-price">
        💰 ราคาทองปัจจุบัน: 4,495.00 USD/oz [web:17]<br>
        <small>Trend: Bullish Bias (D1) แต่ย่อตัวแรง (H1/M15) [web:11][web:12]</small>
    </div>

    <h2>📊 หลักการ Multi-TF (Top-Down)</h2>
    <div class="trend-box bullish">
        - D1/H4: กำหนด Bias (Higher highs/lows, EMA50 support ~4,883 USD)<br>
        - H1: หา Order Block / FVG<br>
        - M15/M5: เข้าตาม confluence (EMA20/50 cross + Liquidity Sweep)
    </div>

    <h2>✅ Checklist เข้าเทรด (Live Signals)</h2>
    <table>
        <tr>
            <th>Timeframe</th>
            <th>Setup</th>
            <th>Entry Rule</th>
            <th>Risk Management</th>
            <th>Status Mar 2026</th>
        </tr>
        <tr class="bullish">
            <td>D1/H4</td>
            <td>Trend bias</td>
            <td>Long > EMA50</td>
            <td>SL 1%, RR 1:2+</td>
            <td>🟢 Bullish (Target 5,400)</td>
        </tr>
        <tr>
            <td>H1</td>
            <td>Order Block/FVG</td>
            <td>รอ confluence</td>
            <td>0.5-1% risk</td>
            <td>🟡 Wait Pullback</td>
        </tr>
        <tr class="bullish">
            <td>M15/M5</td>
            <td>EMA Cross</td>
            <td>ตาม Bias สูง</td>
            <td>Multi TP (50/30/20%)</td>
            <td>🟢 Buy on Dip</td>
        </tr>
    </table>

    <h2>🎯 Trade Plan ปัจจุบัน (29 Mar 2026)</h2>
    <ul>
        <li><strong>Long Setup:</strong> Buy > 4,520 | SL: 4,450 | TP1: 4,650 (50%), TP2: 4,850 (30%), TP3: 5,100 (20%) [web:13]</li>
        <li><strong>Key Levels:</strong> Support 4,400 / Resistance 4,600-4,883 [web:15]</li>
        <li><strong>News Impact:</strong> Fed Rate + Geopolitics หนุน bullish [web:11]</li>
    </ul>

    <h2>⚠️ Risk Warning</h2>
    <p>นี่เป็นกลยุทธ์เพื่อการศึกษา ไม่ใช่คำแนะนำการลงทุน ใช้ MM เสมอ Backtest ก่อน live [web:5].</p>

    <footer style="text-align: center; margin-top: 40px; color: #666;">
        Generated by Perplexity | Data from TradingView/Economics [web:17] | v23 - Mar 29, 2026
    </footer>
</body>
</html>
